namespace cjuridico.Domain.Models.Enuns;

public enum ETipoDeRequerimento
{
    INSTRUCAOEJULGAMENTO,
    CONCILIACAO,
    UNA,
    PARCIAL,
    INTEGRAL,
    FISICO,
    ELETRONICO,
    DESPACHO,
    DILIGENCIAEMCARTORIO,
    EXTRAJUDICIAL,
    HOMOLOGACAO,
    NOTIFICACAO,
    RETIRADAEENVIO,
    RETIRADAELEVANTAMENTO,
    EMISSAODEGUIA,
    EMISSAODECERTIDAO,
    PETICAOINICIAL,
    CARTAPRECATORIA
}